version: '3.9'
services:

  wordpress:
    # default port 9000 (FastCGI)
    image: wordpress:5-fpm
    container_name: wp-wordpress
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - database
    volumes:
      # - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - wordpress-main:/var/www/html
      - wordpress-wp-plugins:/var/www/html/wp-content/plugins
      - wordpress-wp-themes:/var/www/html/wp-content/themes
      # - wordpress-wp-uploads:/var/www/html/wp-content/uploads
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

  database:
    # default port 3306
    extends:
      file: ../mysql/docker-mysql.yml
      service: database
    networks:
      - wordpress

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    container_name: wp-nginx
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - 80:80 
      - 443:443
    volumes:
      # - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - wordpress-main:/var/www/html
      - wordpress-wp-plugins:/var/www/html/wp-content/plugins
      - wordpress-wp-themes:/var/www/html/wp-content/themes
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx

  # adminer - bring up only as needed - bypasses nginx
#  adminer:
#    # default port 8080
#    image: adminer:4
#    container_name: wp-adminer
#    restart: unless-stopped
#    networks:
#      - wordpress
#    depends_on:
#      - database
#    ports:
#      - "9000:8080"
volumes:
  dbdata: {}
  wordpress-main:
  wordpress-wp-plugins:
  wordpress-wp-themes:
networks:
  wordpress:
    name: wp-wordpress
    driver: bridge