services:
  database:
    # default port 3306
    image: mysql:8
    container_name: wp-database
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      # - ${MYSQL_LOCAL_HOME}:/var/lib/mysql
      - dbdata:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'